version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: yatra_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - yatra_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  yatra_mysql_data:
