import { useState } from 'react';
import { MapPin, RotateCcw, Sparkles } from 'lucide-react';
import { api } from '../../services/api';
import { Button, Card, EmptyState, PageHeader, PageLayout } from '../../components/ui';
const templates = [{ destination: 'Kedarnath', days: 7, budget: 50000, name: 'Char Dham Yatra', meta: 'Religious · Uttarakhand', emoji: '🕉️' }, { destination: 'Goa', days: 5, budget: 30000, name: 'Goa Beach Retreat', meta: 'Leisure · West India', emoji: '🌊' }, { destination: 'Rajasthan', days: 8, budget: 80000, name: 'Royal Rajasthan', meta: 'Heritage · Rajasthan', emoji: '🏰' }];
export default function AiItineraryPage() {
  const [destination, setDestination] = useState(''); const [days, setDays] = useState('7'); const [budget, setBudget] = useState(''); const [loading, setLoading] = useState(false); const [result, setResult] = useState(null); const [error, setError] = useState('');
  const fill = template => { setDestination(template.destination); setDays(String(template.days)); setBudget(String(template.budget)); setResult(null); setError(''); };
  const generate = async () => { if (!destination.trim()) return setError('Enter a destination to generate an itinerary.'); setError(''); setLoading(true); setResult(null); try { setResult(await api.agency.generateItinerary(destination.trim(), Number.parseInt(days) || 7, Number.parseFloat(budget) || 0)); } catch (err) { setError(err.message || 'Failed to generate itinerary. Please try again.'); } finally { setLoading(false); } };
  return <PageLayout><section className="agency-ai-hero"><PageHeader eyebrow="Yatra Intelligence" title="Build a thoughtful itinerary in moments." description="Give the destination, trip length, and budget. Yatra AI turns them into a day-wise travel plan." /><div className="agency-ai-form">{error && <p className="agency-form-error">{error}</p>}<label>Destination<input value={destination} onChange={event => setDestination(event.target.value)} placeholder="Kedarnath, Rajasthan, Goa…" /></label><label>Days<input type="number" min="1" max="30" value={days} onChange={event => setDays(event.target.value)} /></label><label>Budget (₹)<input type="number" min="0" value={budget} onChange={event => setBudget(event.target.value)} placeholder="50,000" /></label><Button icon={Sparkles} onClick={generate} disabled={loading}>{loading ? 'Generating…' : 'Generate itinerary'}</Button></div></section>{!result && !loading && <><PageHeader title="Start with a popular route" /><div className="agency-card-grid">{templates.map(template => <Card key={template.destination} className="agency-template-card" onClick={() => fill(template)}><span>{template.emoji}</span><h2>{template.name}</h2><p>{template.meta} · {template.days} days</p></Card>)}</div></>}{result && <div className="agency-itinerary-grid"><section><div className="agency-itinerary-heading"><PageHeader title={`${result.destination || destination} · ${result.days || days}-day itinerary`} /><Button variant="outline" icon={RotateCcw} onClick={() => setResult(null)}>New plan</Button></div>{(result.itinerary || []).length ? result.itinerary.map((day, index) => <Card key={index} className="agency-day-card" padded={false}><header><div><small>Day {day.day || index + 1}</small><h2>{day.title || day.summary || 'Day plan'}</h2></div>{day.estimated_cost != null && <strong>₹{Number(day.estimated_cost).toLocaleString('en-IN')}</strong>}</header><div>{(day.activities || []).map((activity, activityIndex) => <div className="agency-activity" key={activityIndex}>{activity.time && <time>{activity.time}</time>}<div><b>{activity.name || activity.title}</b>{activity.description && <p>{activity.description}</p>}</div></div>)}{!day.activities?.length && day.description && <p>{day.description}</p>}</div></Card>) : <EmptyState icon={MapPin} title="No itinerary details returned" message="Try refining the destination or budget." />}</section><Card className="agency-budget-card"><small>AI budget estimate</small><h2>₹{Number(result.estimated_budget || result.total_budget || 0).toLocaleString('en-IN')}</h2>{Object.entries(result.budget_breakdown || {}).map(([label, value]) => <div key={label}><span>{label}</span><strong>₹{Number(value).toLocaleString('en-IN')}</strong></div>)}{result.notes && <p>{result.notes}</p>}</Card></div>}</PageLayout>;
}
